### PR TITLE
Bump packages

### PR DESCRIPTION
**Pull request by danielmpetrov**
Resolves #395

### CODE REVIEW

**Comment by sebastienros** [comment]
Maybe run the benchmarks with this PR, that's mostly the only reason for these dependencies.

**Comment by danielmpetrov** [comment]
``` ini

BenchmarkDotNet=v0.13.2, OS=Windows 10 (10.0.19044.2130/21H2/November2021Update)
AMD Ryzen 5 2600X, 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.401
  [Host]     : .NET 6.0.9 (6.0.922.41905), X64 RyuJIT AVX2
  DefaultJob : .NET 6.0.9 (6.0.922.41905), X64 RyuJIT AVX2


```
|             Method |          Mean |       Error |      StdDev |  Ratio | RatioSD |      Gen0 |     Gen1 |    Gen2 |   Allocated | Alloc Ratio |
|------------------- |--------------:|------------:|------------:|-------:|--------:|----------:|---------:|--------:|------------:|------------:|
|        Fluid_Parse |      7.929 μs |   0.0617 μs |   0.0547 μs |   1.00 |    0.00 |    0.6561 |        - |       - |     2.68 KB |        1.00 |
|      Scriban_Parse |     12.641 μs |   0.0762 μs |   0.0675 μs |   1.59 |    0.01 |    1.8311 |        - |       - |     7.51 KB |        2.80 |
|    DotLiquid_Parse |     23.788 μs |   0.1306 μs |   0.1158 μs |   3.00 |    0.02 |    3.9673 |        - |       - |    16.21 KB |        6.05 |
|    LiquidNet_Parse |    109.340 μs |   1.4663 μs |   1.3715 μs |  13.79 |    0.16 |   15.1367 |   0.1221 |       - |    62.08 KB |       23.17 |
|   Handlebars_Parse |  3,617.641 μs |  25.8260 μs |  20.1632 μs | 456.16 |    4.13 |   39.0625 |  11.7188 |       - |   163.08 KB |       60.86 |
|                    |               |             |             |        |         |           |          |         |             |             |
|     Fluid_ParseBig |     41.155 μs |   0.1501 μs |   0.1253 μs |   1.00 |    0.00 |    2.8076 |        - |       - |    11.61 KB |        1.00 |
|   Scriban_ParseBig |     65.440 μs |   0.8304 μs |   0.7767 μs |   1.59 |    0.02 |    8.3008 |        - |       - |    34.17 KB |        2.94 |
| DotLiquid_ParseBig |     90.971 μs |   1.0512 μs |   0.9833 μs |   2.21 |    0.02 |   23.0713 |        - |       - |    94.37 KB |        8.13 |
| LiquidNet_ParseBig | 30,935.784 μs | 218.6240 μs | 204.5010 μs | 752.26 |    4.80 | 6812.5000 | 343.7500 |       - | 28543.66 KB |    2,458.67 |
|                    |               |             |             |        |         |           |          |         |             |             |
|       Fluid_Render |    453.500 μs |   5.5464 μs |   5.1881 μs |   1.00 |    0.00 |   22.9492 |   2.9297 |       - |    95.87 KB |        1.00 |
|     Scriban_Render |  1,906.807 μs |  33.3947 μs |  31.2374 μs |   4.21 |    0.08 |  103.5156 |  68.3594 | 68.3594 |   498.42 KB |        5.20 |
|   DotLiquid_Render |  3,835.848 μs |  20.3869 μs |  18.0725 μs |   8.45 |    0.12 |  718.7500 | 140.6250 | 31.2500 |  3371.01 KB |       35.16 |
|   LiquidNet_Render |  2,515.277 μs |  20.9363 μs |  19.5838 μs |   5.55 |    0.07 |  515.6250 | 257.8125 |       - |  3144.39 KB |       32.80 |
|  Handlebars_Render |    543.648 μs |   3.4845 μs |   3.0889 μs |   1.20 |    0.02 |   46.8750 |  11.7188 |       - |   194.93 KB |        2.03 |

**Comment by danielmpetrov** [comment]
These are the results I got, should I update the readme accordingly?

**Comment by sebastienros** [comment]
@danielmpetrov yes please update the benchmarks table

**Comment by danielmpetrov** [comment]
@sebastienros Updated benchmarks summary and results table. 👍

**Comment by sebastienros** [comment]
I am adding the triple back ticks back, I think it's more readable than the html table.

**Pull request merged**
