### PR TITLE
Fix incomplete statement await in IfStatement

### PR DESCRIPTION
**Pull request by lahma**

### CODE REVIEW

**Comment by jptissot** [comment]
This fixes both: 
https://github.com/OrchardCMS/OrchardCore/issues/9222
https://github.com/OrchardCMS/OrchardCore/issues/9223

**Comment by hishamco** [comment]
We need a release to close them

**Comment by sebastienros** [comment]
Done

**Comment by hishamco** [comment]
PR is created in OC

Thanks

**Pull request merged**
