### PR TITLE
Added Sum ArrayFilter with 2 different options

### PR DESCRIPTION
**Pull request by cpriestland**
Added "Sum" ArrayFilter so that others can use it also.

2 options:

- Can include an argument to indicate which member to Sum on an array of objects
- No argument which will attempt to Sum the array items value

Tests included with Pull Request which check both of these scenario's

We use Fluid quite a lot at TemplateTo and hope you don't mind us putting our link in your UsedBy section, Fluid can be used by our users as well when building out their templates.

### CODE REVIEW

**Review by hishamco — APPROVED** [review]

**Comment by cpriestland** [comment]
@hishamco Thanks for approving this, is there an idea of when this could be merged as we require the functionality? Thanks

**Comment by sebastienros** [comment]
Would you mind adding the same tests as in Shopify Liquid to ensure everything behaves as the specs?
https://github.com/Shopify/liquid/blob/f5ed5404b5ba04c7010d4f37ca2928bb6fa925a2/test/integration/standard_filter_test.rb#L952-L1052

**Comment by cpriestland** [comment]
Thanks for your reply @sebastienros I have added the tests as suggested

**Comment by hishamco** [comment]
Thanks for your contribution @cpriestland

**Pull request merged**
