### PR TITLE
Liquid within comment should not be executed

### PR DESCRIPTION
**Pull request by hishamco**
Address issue #26

### CODE REVIEW

**Comment by sebastienros** [comment]
Why is Include the only tag that behaves like this. Sounds like an issue with this tag.

**Comment by hishamco** [comment]
This is the workaround that I come up with, that main reason behind this, because the `include` called `TryParse()` for the partial after the `{% endcomment %}` has been closed

Refer to [this](https://github.com/sebastienros/fluid/pull/29/files#diff-9de51dea2a4e6978c5be0829c3c9a06bR62)

**Comment by hishamco** [comment]
IMHO workaround is acceptable, until we find a better way

**Comment by sebastienros** [comment]
Can't be accepted as a workaround as it's not an issue for include tags only.

**Comment by hishamco** [comment]
I saw this issue occurs only for `include` tag!!

**Pull request closed without merging**
