### PR TITLE
Implement paginate tag

### PR DESCRIPTION
**Pull request by Soar360**
#247

### CODE REVIEW

**Comment by hishamco** [comment]
Could you please add some unit tests to test corner cases and to ensure that the `paginate` tage works as expected?

**Comment by Soar360** [comment]
OK, I'll try.

**Comment by hishamco** [comment]
Great job @Soar360, before I move into formatting issues ;) your PR looks good to me, but these some initial comments

- All the Fluid filters should be `Fluid.Filters` namespace

- All the Fluid values should be `Fluid.Values` namespace

- We should make the pagination labels customizable

@sebastienros could please have a quick look to the PR and share your thoughts

**Comment by bryan07** [comment]
Is this going to happen?

**Comment by bryan07** [comment]
Is this going to happen?

**Comment by nathanaskinner** [comment]
any update on this?

**Comment by hishamco** [comment]
@Soar360 please resolve the conflict

**Comment by Soar360** [comment]
I will recreate a PR to solve this problem

**Comment by hishamco** [comment]
No need to can pull and fix the merge conflict

**Comment by Soar360** [comment]
I have a new solution ,please wait.

**Pull request closed without merging**
