### PR TITLE
Ignore tags in raw and comment blocks

### LINKED ISSUE #26: Liquid within comment executes
Should Liquid within a comment still execute or should a comment prevent execution? For Shopify's implementation, code will not execute:

> comment
> Allows you to leave un-rendered code inside a Liquid template. Any text within the opening and closing comment blocks will not be output, and any Liquid code within will not be executed. https://help.shopify.com/themes/liquid/tags/theme-tags#comment

Fluid example:

    {% comment %}
    I don't get printed but this code is executed. That is, `programs` is assigned a value, and all that.
    {% assign programs = '[ {"id": 1, "iconUrl": "http://lorempixel.com/output/animals-q-c-640-480-3.jpg", "title": "One" } ]' | parse %}
    {% endcomment %}

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #26

### CODE REVIEW

**Comment by sebastienros** [comment]
Welcoming your review @hishamco

**Comment by hishamco** [comment]
Can we add a test similar to [this](https://github.com/sebastienros/fluid/pull/34/files#diff-d6ec8a3529c92d09f8940f27153bfab4R450)?

**Comment by hishamco** [comment]
LGTM

**Comment by sebastienros** [comment]
I understand why we could add a test like you suggest, but the unit tests I wrote ensure that just the raw text is analyzed. So I think we are well covered.

**Pull request merged**
