### PR TITLE
Multitarget Netstandard 2.0 and added VB.NET example project

### PR DESCRIPTION
**Pull request by TheConservativeCoder**
Hi Sebastien,

I have set this up to multi target netstandard 2.0 and have added an example VB.NET Web App project that mirrors your original C# one.

### CODE REVIEW

**Comment by sebastienros** [comment]
Looks good. I don't think the VB sample adds any value though.

**Comment by hishamco** [comment]
I'm a VB fan 😄 , I think VB in good at this point, it shows that Fluid supports both VB.NET & C#, while Razor in ASP.NET Core still 😞

**Comment by sebastienros** [comment]
I beleive if it support netstandard2.0 then it supports VB ? Any Vb user would know that without having to search for a specific Vb sample.

**Comment by hishamco** [comment]
> I beleive if it support netstandard2.0 then it supports VB ?

But not for the Web, while the Razor using .chtml only

> Any Vb user would know that without having to search for a specific Vb sample.

Yep, but I think it's good to let the audience recognize that Fluid is not language dependent, as what we have seen in the Razor in ASP.NET Core

IMHO leaving the sample is fine, but the final word to you

**Comment by hishamco** [comment]
@sebastienros can you take the right decision about this?

**Comment by sebastienros** [comment]
1- I don't care about the Vb sample, I can add a mention in the readme to say it's supported
2- It already works in a Vb application, I just tried

Do we still need to target netstandard2.0 for any reason?

**Comment by hishamco** [comment]
> Do we still need to target netstandard2.0 for any reason?

I don't think so

**Comment by TheConservativeCoder** [comment]
Cool, I'll delete this

**Pull request closed without merging**
