### PR TITLE
Add replace_last and remove_last filters

### LINKED ISSUE #494: Implement replace_last and replace_first filters
https://github.com/Shopify/liquid/pull/1422

### PR DESCRIPTION
**Pull request by danielmpetrov**
Bonus - add a missing assert statement in `RemovesReturnsInputWhenArgumentIsEmpty` unit test.

Resolve #494

### CODE REVIEW

**Comment by sebastienros** [comment]
Awesome!

Can you also add the missing test cases from here:
https://github.com/Shopify/liquid/pull/1422/files#diff-783fde0f471731937b1ede37eff3107dae698e98dc76dda994391f49ca73958aR542-R566

This contains some with types that are not strings (I see it's implemented but not tested).

**Comment by danielmpetrov** [comment]
Thanks for the quick feedback.

No problem, I can add those. Need to run now, but will update the PR later today or likely tomorrow.

**Comment by hishamco** [comment]
Can you use `Theory` instead to examine different use cases for both unit tests

**Comment by hishamco** [comment]
Can you use `Theory` instead to examine different use cases for both unit tests

**Comment by sebastienros** [comment]
I added an extra unit test

**Pull request merged**
